### ISSUE TITLE
What modules does the module need in order to run?

### ISSUE THREAD

**Issue by bornel2024** [ClayGolemDM/cg-Curse-of-Strahd#1]
I am getting this message, what should i do?

![image](https://github.com/user-attachments/assets/7985dce0-9aa4-41cb-a337-982d8c277d63)

**Comment by ClayGolemDM** [comment]
Hi.

Sorry you're encountering problems. I thought I put that in the release
notes, but to clarify, you will need the following Mods installed:

Item Piles
lib wrapper
Monk's Active Tile Triggers
socket lib
Tagger

I've tried to keep the list as short as possible.
Let me know if you encounter any further issues and I'll do what I can to
fix.


CG
