### ISSUE TITLE
Getting VTT Error:[undefined] Cannot read properties of null (reading 'id) when trying to load Module

### ISSUE THREAD

**Issue by lonewookieman** [ClayGolemDM/cg-Curse-of-Strahd#2]
I have just setup a new VTT Server and loaded the prerequisites as listed in the readme.  When I try load the Curse of Strahd module I am getting this error.

Error:[undefined] Cannot read properties of null (reading 'id)

**Comment by ClayGolemDM** [comment]
Urgh! That sucks. I've just downloaded it myself on a fresh install using this link in the Manifest URL: https://github.com/ClayGolemDM/cg-Curse-of-Strahd/releases/download/0.2.4/module.json and did not encounter a problem. 

Assuming you're getting that error when you're in the game and trying to activate the CoS module?

Can you ensure you have the extra mods (LibWrapper, Item Piles, MATTs, socketlib and Tagger active in the world, and then activate CoS?

**Comment by lonewookieman** [comment]
Thanks the link you provided worked, I apparently had the wrong link to the module.json file.  I did have the extra mods installed before I tried initially.  Thanks for the assist.
